# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ivona/FER/Projekt/pink

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ivona/FER/Projekt/pink

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ivona/FER/Projekt/pink/CMakeFiles /home/ivona/FER/Projekt/pink/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ivona/FER/Projekt/pink/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pink_alignment

# Build rule for target.
pink_alignment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pink_alignment
.PHONY : pink_alignment

# fast build rule for target.
pink_alignment/fast:
	$(MAKE) -f CMakeFiles/pink_alignment.dir/build.make CMakeFiles/pink_alignment.dir/build
.PHONY : pink_alignment/fast

#=============================================================================
# Target rules for targets named pink_mapper

# Build rule for target.
pink_mapper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pink_mapper
.PHONY : pink_mapper

# fast build rule for target.
pink_mapper/fast:
	$(MAKE) -f CMakeFiles/pink_mapper.dir/build.make CMakeFiles/pink_mapper.dir/build
.PHONY : pink_mapper/fast

#=============================================================================
# Target rules for targets named pink_mapper_test

# Build rule for target.
pink_mapper_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pink_mapper_test
.PHONY : pink_mapper_test

# fast build rule for target.
pink_mapper_test/fast:
	$(MAKE) -f CMakeFiles/pink_mapper_test.dir/build.make CMakeFiles/pink_mapper_test.dir/build
.PHONY : pink_mapper_test/fast

#=============================================================================
# Target rules for targets named zlibstatic

# Build rule for target.
zlibstatic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlibstatic
.PHONY : zlibstatic

# fast build rule for target.
zlibstatic/fast:
	$(MAKE) -f vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/build.make vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/build
.PHONY : zlibstatic/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) -f vendor/bioparser/vendor/zlib/CMakeFiles/zlib.dir/build.make vendor/bioparser/vendor/zlib/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) -f vendor/bioparser/vendor/zlib/CMakeFiles/example.dir/build.make vendor/bioparser/vendor/zlib/CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named minigzip

# Build rule for target.
minigzip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minigzip
.PHONY : minigzip

# fast build rule for target.
minigzip/fast:
	$(MAKE) -f vendor/bioparser/vendor/zlib/CMakeFiles/minigzip.dir/build.make vendor/bioparser/vendor/zlib/CMakeFiles/minigzip.dir/build
.PHONY : minigzip/fast

#=============================================================================
# Target rules for targets named minigzip64

# Build rule for target.
minigzip64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minigzip64
.PHONY : minigzip64

# fast build rule for target.
minigzip64/fast:
	$(MAKE) -f vendor/bioparser/vendor/zlib/CMakeFiles/minigzip64.dir/build.make vendor/bioparser/vendor/zlib/CMakeFiles/minigzip64.dir/build
.PHONY : minigzip64/fast

#=============================================================================
# Target rules for targets named example64

# Build rule for target.
example64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example64
.PHONY : example64

# fast build rule for target.
example64/fast:
	$(MAKE) -f vendor/bioparser/vendor/zlib/CMakeFiles/example64.dir/build.make vendor/bioparser/vendor/zlib/CMakeFiles/example64.dir/build
.PHONY : example64/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f vendor/googletest/googletest/CMakeFiles/gtest_main.dir/build.make vendor/googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f vendor/googletest/googletest/CMakeFiles/gtest.dir/build.make vendor/googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

src/pink_alignment.o: src/pink_alignment.cpp.o

.PHONY : src/pink_alignment.o

# target to build an object file
src/pink_alignment.cpp.o:
	$(MAKE) -f CMakeFiles/pink_alignment.dir/build.make CMakeFiles/pink_alignment.dir/src/pink_alignment.cpp.o
.PHONY : src/pink_alignment.cpp.o

src/pink_alignment.i: src/pink_alignment.cpp.i

.PHONY : src/pink_alignment.i

# target to preprocess a source file
src/pink_alignment.cpp.i:
	$(MAKE) -f CMakeFiles/pink_alignment.dir/build.make CMakeFiles/pink_alignment.dir/src/pink_alignment.cpp.i
.PHONY : src/pink_alignment.cpp.i

src/pink_alignment.s: src/pink_alignment.cpp.s

.PHONY : src/pink_alignment.s

# target to generate assembly for a file
src/pink_alignment.cpp.s:
	$(MAKE) -f CMakeFiles/pink_alignment.dir/build.make CMakeFiles/pink_alignment.dir/src/pink_alignment.cpp.s
.PHONY : src/pink_alignment.cpp.s

src/pink_mapper.o: src/pink_mapper.cpp.o

.PHONY : src/pink_mapper.o

# target to build an object file
src/pink_mapper.cpp.o:
	$(MAKE) -f CMakeFiles/pink_mapper.dir/build.make CMakeFiles/pink_mapper.dir/src/pink_mapper.cpp.o
.PHONY : src/pink_mapper.cpp.o

src/pink_mapper.i: src/pink_mapper.cpp.i

.PHONY : src/pink_mapper.i

# target to preprocess a source file
src/pink_mapper.cpp.i:
	$(MAKE) -f CMakeFiles/pink_mapper.dir/build.make CMakeFiles/pink_mapper.dir/src/pink_mapper.cpp.i
.PHONY : src/pink_mapper.cpp.i

src/pink_mapper.s: src/pink_mapper.cpp.s

.PHONY : src/pink_mapper.s

# target to generate assembly for a file
src/pink_mapper.cpp.s:
	$(MAKE) -f CMakeFiles/pink_mapper.dir/build.make CMakeFiles/pink_mapper.dir/src/pink_mapper.cpp.s
.PHONY : src/pink_mapper.cpp.s

test/pink_mapper_test.o: test/pink_mapper_test.cpp.o

.PHONY : test/pink_mapper_test.o

# target to build an object file
test/pink_mapper_test.cpp.o:
	$(MAKE) -f CMakeFiles/pink_mapper_test.dir/build.make CMakeFiles/pink_mapper_test.dir/test/pink_mapper_test.cpp.o
.PHONY : test/pink_mapper_test.cpp.o

test/pink_mapper_test.i: test/pink_mapper_test.cpp.i

.PHONY : test/pink_mapper_test.i

# target to preprocess a source file
test/pink_mapper_test.cpp.i:
	$(MAKE) -f CMakeFiles/pink_mapper_test.dir/build.make CMakeFiles/pink_mapper_test.dir/test/pink_mapper_test.cpp.i
.PHONY : test/pink_mapper_test.cpp.i

test/pink_mapper_test.s: test/pink_mapper_test.cpp.s

.PHONY : test/pink_mapper_test.s

# target to generate assembly for a file
test/pink_mapper_test.cpp.s:
	$(MAKE) -f CMakeFiles/pink_mapper_test.dir/build.make CMakeFiles/pink_mapper_test.dir/test/pink_mapper_test.cpp.s
.PHONY : test/pink_mapper_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... pink_alignment"
	@echo "... pink_mapper"
	@echo "... pink_mapper_test"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... zlibstatic"
	@echo "... zlib"
	@echo "... example"
	@echo "... minigzip"
	@echo "... minigzip64"
	@echo "... example64"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... src/pink_alignment.o"
	@echo "... src/pink_alignment.i"
	@echo "... src/pink_alignment.s"
	@echo "... src/pink_mapper.o"
	@echo "... src/pink_mapper.i"
	@echo "... src/pink_mapper.s"
	@echo "... test/pink_mapper_test.o"
	@echo "... test/pink_mapper_test.i"
	@echo "... test/pink_mapper_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

